@baseUrl = http://localhost:3333
@authToken = {{login.response.body.data.accessToken}}


# @name registerUser
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"username": "JohnDoe6",
	"firstName": "john",
	"lastName" : "Doe",
	"email": "johndoe6@gmail.com",
	"password": "12345678"
}

###

# @name login

POST {{baseUrl}}/login
Content-Type: application/json

{
	"login": "JohnDoe3",
	"password": "12345678"
}

###

# @name  createHealthUnit

POST {{baseUrl}}/healthunits
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "unidade2",
	"city": "Ananindeua",
	"state": "PA",
	"latitude": -100000,
	"longitude": -99999
}

###