services:
  postgres:
    container_name: healthfind-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/pg:/data/postgres